/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as AuthDiscordRouteImport } from './routes/auth.discord'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalAchievementsRouteImport } from './routes/portal.achievements'
import { Route as PortalDiscordRouteImport } from './routes/portal.discord'
import { Route as PortalEventsRouteImport } from './routes/portal.events'
import { Route as PortalMembershipRouteImport } from './routes/portal.membership'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalStatsRouteImport } from './routes/portal.stats'
import { Route as AuthDiscordCallbackRouteImport } from './routes/auth.discord.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDiscordRoute = AuthDiscordRouteImport.update({
  id: '/auth/discord',
  path: '/auth/discord',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAchievementsRoute = PortalAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDiscordRoute = PortalDiscordRouteImport.update({
  id: '/discord',
  path: '/discord',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventsRoute = PortalEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMembershipRoute = PortalMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatsRoute = PortalStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PortalRoute,
} as any)
const AuthDiscordCallbackRoute = AuthDiscordCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthDiscordRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/auth/discord': typeof AuthDiscordRouteWithChildren
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/discord': typeof PortalDiscordRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/membership': typeof PortalMembershipRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/stats': typeof PortalStatsRoute
  '/portal/': typeof PortalIndexRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/play': typeof PlayRoute
  '/worlds': typeof WorldsRoute
  '/auth/discord': typeof AuthDiscordRouteWithChildren
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/discord': typeof PortalDiscordRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/membership': typeof PortalMembershipRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/stats': typeof PortalStatsRoute
  '/portal': typeof PortalIndexRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/events': typeof EventsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/play': typeof PlayRoute
  '/portal': typeof PortalRouteWithChildren
  '/worlds': typeof WorldsRoute
  '/auth/discord': typeof AuthDiscordRouteWithChildren
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/discord': typeof PortalDiscordRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/membership': typeof PortalMembershipRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/stats': typeof PortalStatsRoute
  '/portal/': typeof PortalIndexRoute
  '/auth/discord/callback': typeof AuthDiscordCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/events'
    | '/leaderboards'
    | '/live'
    | '/login'
    | '/membership'
    | '/play'
    | '/portal'
    | '/worlds'
    | '/auth/discord'
    | '/portal/achievements'
    | '/portal/discord'
    | '/portal/events'
    | '/portal/membership'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/stats'
    | '/portal/'
    | '/auth/discord/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/events'
    | '/leaderboards'
    | '/live'
    | '/login'
    | '/membership'
    | '/play'
    | '/worlds'
    | '/auth/discord'
    | '/portal/achievements'
    | '/portal/discord'
    | '/portal/events'
    | '/portal/membership'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/stats'
    | '/portal'
    | '/auth/discord/callback'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/events'
    | '/leaderboards'
    | '/live'
    | '/login'
    | '/membership'
    | '/play'
    | '/portal'
    | '/worlds'
    | '/auth/discord'
    | '/portal/achievements'
    | '/portal/discord'
    | '/portal/events'
    | '/portal/membership'
    | '/portal/profile'
    | '/portal/settings'
    | '/portal/stats'
    | '/portal/'
    | '/auth/discord/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  EventsRoute: typeof EventsRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  PlayRoute: typeof PlayRoute
  PortalRoute: typeof PortalRouteWithChildren
  WorldsRoute: typeof WorldsRoute
  AuthDiscordRoute: typeof AuthDiscordRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/discord': {
      id: '/auth/discord'
      path: '/auth/discord'
      fullPath: '/auth/discord'
      preLoaderRoute: typeof AuthDiscordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/achievements': {
      id: '/portal/achievements'
      path: '/achievements'
      fullPath: '/portal/achievements'
      preLoaderRoute: typeof PortalAchievementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/discord': {
      id: '/portal/discord'
      path: '/discord'
      fullPath: '/portal/discord'
      preLoaderRoute: typeof PortalDiscordRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/events': {
      id: '/portal/events'
      path: '/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof PortalEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/membership': {
      id: '/portal/membership'
      path: '/membership'
      fullPath: '/portal/membership'
      preLoaderRoute: typeof PortalMembershipRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/stats': {
      id: '/portal/stats'
      path: '/stats'
      fullPath: '/portal/stats'
      preLoaderRoute: typeof PortalStatsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/auth/discord/callback': {
      id: '/auth/discord/callback'
      path: '/callback'
      fullPath: '/auth/discord/callback'
      preLoaderRoute: typeof AuthDiscordCallbackRouteImport
      parentRoute: typeof AuthDiscordRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAchievementsRoute: typeof PortalAchievementsRoute
  PortalDiscordRoute: typeof PortalDiscordRoute
  PortalEventsRoute: typeof PortalEventsRoute
  PortalMembershipRoute: typeof PortalMembershipRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalStatsRoute: typeof PortalStatsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAchievementsRoute: PortalAchievementsRoute,
  PortalDiscordRoute: PortalDiscordRoute,
  PortalEventsRoute: PortalEventsRoute,
  PortalMembershipRoute: PortalMembershipRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalStatsRoute: PortalStatsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface AuthDiscordRouteChildren {
  AuthDiscordCallbackRoute: typeof AuthDiscordCallbackRoute
}

const AuthDiscordRouteChildren: AuthDiscordRouteChildren = {
  AuthDiscordCallbackRoute: AuthDiscordCallbackRoute,
}

const AuthDiscordRouteWithChildren = AuthDiscordRoute._addFileChildren(
  AuthDiscordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  EventsRoute: EventsRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  PlayRoute: PlayRoute,
  PortalRoute: PortalRouteWithChildren,
  WorldsRoute: WorldsRoute,
  AuthDiscordRoute: AuthDiscordRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
